### ISSUE TITLE
Create a scenario with the agent set on a IPv6 address.

### ISSUE THREAD

**Issue by mhlidd** [DataDog/system-tests#3549]
I'm looking to write a parametric test for the following [ticket](https://datadoghq.atlassian.net/browse/APMAPI-869) where we want to see whether setting an agent to an IPv6 address will lead to issues in the tracer. Could you point me towards how to customize an agent in the system-tests repo to use IPv6 and how to have a tracer point to it?

**Comment by mhlidd** [comment]
Weblog makes sense to me here then. I believe it will cover all scenarios that I am concerned with. Just to double check, there are no prerequisite steps to using a weblog scenario with IPv6 right? I just start with setting a `DD_AGENT_HOST` and shouldn't encounter any issues?

**Comment by cbeauchesne** [comment]
By default, the docker network use IPv4. You could use a IPv4 translated to IPv6, and it should works. But you need to get the agent IP address, so it'll requires a few extra bit.

Though, I think we should go the ambitious way, and use a real IPv6, because I strongly suspect that a translated IPv4 address will be converted back by some network layer. So having a real IPv6 address is better IMO
